# Generated by Django 4.1.7 on 2023-03-31 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('complete', models.BooleanField(default=False, help_text='Complete', verbose_name='Complete')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created at', verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['complete'],
            },
        ),
    ]
